server:
  port: 8081
spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://localhost:3306/spinach?useSSL=false&characterEncoding=utf8&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver